enum EnvKeys {
  PORT = 'PORT',
  API_PREFIX = 'API_PREFIX',
  LOG_FILE_ENABLE = 'LOG_FILE_ENABLE',
  CONNECT_DATABASE = 'CONNECT_DATABASE',
  DATABASE_CONN_NAME = 'DATABASE_CONN_NAME',
}

export default EnvKeys;
